### PR TITLE
fixing for memory leak: gaia_result_modifiers

### PR DESCRIPTION
**Pull request by zapion**
Another workaround for memory leak issue

### CODE REVIEW

**Comment by zapion** [comment]
@Walter @ShakoHo  r?

**Comment by walter** [comment]
I think you mean @ypwalter, not me.

**Comment by ShakoHo** [comment]
it works great in my local environment, after 15 hrs running, the RSS consumption is around 27MB....
r+

**Comment by ypwalter** [comment]
@walter, thanks for clarification

**Pull request merged**
